In [1]:
import pandas as pd

In [3]:
import os

print(os.getcwd())

C:\Users\User\Downloads\PAPER_LEAK_ANALYSIS

In [6]:
import pandas as pd

df = pd.read_csv("Paper_leaks_India.csv", encoding="cp1252")
df.head()

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Appeared Students
0,26-08-2024,B.Ed. 4th Sem Exam : Creating an Inclusive School,Tamil Nadu Teachers Education University,State,Tamilnadu,accused,Alternative Question Paper Used,Alternative Question Paper Used,Paper leaked on social media before exam,TNTEU registrar relieved after reports of B.Ed...,NaN
1,04-08-2024,MBA 1st year Exam,Pondicherry University,Central,Pondicherry,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Pondicherry University First-year MBBS Exam Pa...,NaN
2,06-07-2024,Foreign Medical Graduate Examination,National Board of Examinations in Medical Scie...,Central,Kerala,accused,Legal action taken and claim dismissed,"No Rexam and checking of evidence, claim dismi...",Paper leaked on social media,‘So far no evidence’: Kerala Police on FMGE ‘p...,NaN
3,30-06-2024,Agriculture Development Officers,Punjab Public Service Comission,State,Punjab,accused,NaN,No Rexam,Claim: Offical demanded bribe for leaking paper,"Now, ADO recruitment exam in Punjab under pape...",NaN
4,18-06-2024,UGC NET 2024,National Testing Agency,Central,All India,accused,No Rexam,Exam cancellation decision overruled by Suprem...,accusation of paper leak,Supreme Court upholds decision to cancel UGC N...,NaN

In [7]:
df.head()

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Appeared Students
0,26-08-2024,B.Ed. 4th Sem Exam : Creating an Inclusive School,Tamil Nadu Teachers Education University,State,Tamilnadu,accused,Alternative Question Paper Used,Alternative Question Paper Used,Paper leaked on social media before exam,TNTEU registrar relieved after reports of B.Ed...,NaN
1,04-08-2024,MBA 1st year Exam,Pondicherry University,Central,Pondicherry,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Pondicherry University First-year MBBS Exam Pa...,NaN
2,06-07-2024,Foreign Medical Graduate Examination,National Board of Examinations in Medical Scie...,Central,Kerala,accused,Legal action taken and claim dismissed,"No Rexam and checking of evidence, claim dismi...",Paper leaked on social media,‘So far no evidence’: Kerala Police on FMGE ‘p...,NaN
3,30-06-2024,Agriculture Development Officers,Punjab Public Service Comission,State,Punjab,accused,NaN,No Rexam,Claim: Offical demanded bribe for leaking paper,"Now, ADO recruitment exam in Punjab under pape...",NaN
4,18-06-2024,UGC NET 2024,National Testing Agency,Central,All India,accused,No Rexam,Exam cancellation decision overruled by Suprem...,accusation of paper leak,Supreme Court upholds decision to cancel UGC N...,NaN

In [8]:
df.tail()

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Appeared Students
61,01-05-2016,NEET Phase 1 2016,CBSE,Central,Uttar Pradesh,confirmed,Legal action taken,No Rexam,Cheating reported,NEET Phase 1 2016: Paper leaked in Varanasi - ...,NaN
62,25-05-2015,UP CPMT 2015,"King George's Medical University , Lucknow",State,Uttar Pradesh,confirmed,Legal action taken,No Rexam,Paper leaked on social media,Bid to leak UP CPMT answers: 3 MBBS students a...,NaN
63,03-05-2015,AIPMT 2015,CBSE,Central,All India,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media,"AIPMT cancelled, CBSE told to reconduct exam -...",NaN
64,30-03-2015,Provincial civil services preliminary examination,Uttar Pradesh Public Service Comission,State,Uttar Pradesh,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Uttar Pradesh civil services exam cancelled af...,NaN
65,23-06-2014,UP CPMT 2014,"King George's Medical University , Ghaziabadd",State,Uttar Pradesh,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media,"CPMT 2014 paper leak: Aspirants dejected, dema...",NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date of Exam/Incident     66 non-null     object
 1   Exam Name                 66 non-null     object
 2   Conducting Body           66 non-null     object
 3   Conducting Body Type      66 non-null     object
 4   Area(s) of Incident       66 non-null     object
 5   Leak Confirmation Status  66 non-null     object
 6   Action taken              64 non-null     object
 7   Note about action Taken   66 non-null     object
 8   Note about incident       66 non-null     object
 9   References                66 non-null     object
 10  Appeared Students         1 non-null      float64
dtypes: float64(1), object(10)
memory usage: 5.8+ KB

In [10]:
df.shape

(66, 11)

In [11]:
df.columns

Index(['Date of Exam/Incident', 'Exam Name', 'Conducting Body',
       'Conducting Body Type', 'Area(s) of Incident',
       'Leak Confirmation Status', 'Action taken', 'Note about action Taken',
       'Note about incident', 'References ', 'Appeared Students'],
      dtype='object')

In [12]:
df.isnull().sum()

Date of Exam/Incident        0
Exam Name                    0
Conducting Body              0
Conducting Body Type         0
Area(s) of Incident          0
Leak Confirmation Status     0
Action taken                 2
Note about action Taken      0
Note about incident          0
References                   0
Appeared Students           65
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.describe()

       Appeared Students
count                1.0
mean               183.0
std                  NaN
min                183.0
25%                183.0
50%                183.0
75%                183.0
max                183.0

In [15]:
df.describe(include='all')

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Appeared Students
count,66,66,66,66,66,66,64,66,66,66,1.0
unique,66,63,53,3,24,2,12,22,29,66,NaN
top,26-08-2024,High School Mathematics Exam,Maharashtra State Board of Secondary and Highe...,State,Uttar Pradesh,confirmed,Exam Cancelled,No Rexam,Paper leaked on social media,TNTEU registrar relieved after reports of B.Ed...,NaN
freq,1,3,3,50,11,48,30,13,28,1,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.0

In [18]:
clean_df = df.copy()

In [19]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date of Exam/Incident     66 non-null     object
 1   Exam Name                 66 non-null     object
 2   Conducting Body           66 non-null     object
 3   Conducting Body Type      66 non-null     object
 4   Area(s) of Incident       66 non-null     object
 5   Leak Confirmation Status  66 non-null     object
 6   Action taken              64 non-null     object
 7   Note about action Taken   66 non-null     object
 8   Note about incident       66 non-null     object
 9   References                66 non-null     object
 10  Appeared Students         1 non-null      float64
dtypes: float64(1), object(10)
memory usage: 5.8+ KB

In [20]:
clean_df = clean_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [21]:
clean_df.head()

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Appeared Students
0,26-08-2024,B.Ed. 4th Sem Exam : Creating an Inclusive School,Tamil Nadu Teachers Education University,State,Tamilnadu,accused,Alternative Question Paper Used,Alternative Question Paper Used,Paper leaked on social media before exam,TNTEU registrar relieved after reports of B.Ed...,NaN
1,04-08-2024,MBA 1st year Exam,Pondicherry University,Central,Pondicherry,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Pondicherry University First-year MBBS Exam Pa...,NaN
2,06-07-2024,Foreign Medical Graduate Examination,National Board of Examinations in Medical Scie...,Central,Kerala,accused,Legal action taken and claim dismissed,"No Rexam and checking of evidence, claim dismi...",Paper leaked on social media,‘So far no evidence’: Kerala Police on FMGE ‘p...,NaN
3,30-06-2024,Agriculture Development Officers,Punjab Public Service Comission,State,Punjab,accused,NaN,No Rexam,Claim: Offical demanded bribe for leaking paper,"Now, ADO recruitment exam in Punjab under pape...",NaN
4,18-06-2024,UGC NET 2024,National Testing Agency,Central,All India,accused,No Rexam,Exam cancellation decision overruled by Suprem...,accusation of paper leak,Supreme Court upholds decision to cancel UGC N...,NaN

In [22]:
clean_df["Action taken"] = clean_df["Action taken"].fillna("Unknown")

In [23]:
clean_df.isnull().sum()

Date of Exam/Incident        0
Exam Name                    0
Conducting Body              0
Conducting Body Type         0
Area(s) of Incident          0
Leak Confirmation Status     0
Action taken                 0
Note about action Taken      0
Note about incident          0
References                   0
Appeared Students           65
dtype: int64

In [24]:
clean_df.duplicated().sum()

np.int64(0)

In [25]:
clean_df.drop(columns=["Appeared Students"], inplace=True)

In [26]:
clean_df["Action taken"] = clean_df["Action taken"].fillna("Unknown")

In [27]:
clean_df.isnull().sum()

Date of Exam/Incident       0
Exam Name                   0
Conducting Body             0
Conducting Body Type        0
Area(s) of Incident         0
Leak Confirmation Status    0
Action taken                0
Note about action Taken     0
Note about incident         0
References                  0
dtype: int64

In [28]:
clean_df["Date of Exam/Incident"].head(15)

0     26-08-2024
1     04-08-2024
2     06-07-2024
3     30-06-2024
4     18-06-2024
5     09-06-2024
6     28-05-2024
7     28-04-2024
8     16-04-2024
9     17-03-2024
10    17-02-2024
11    16-02-2024
12    11-02-2024
13    26-12-2023
14    25-12-2023
Name: Date of Exam/Incident, dtype: object

In [29]:
pd.to_datetime(clean_df["Date of Exam/Incident"])

C:\Users\User\AppData\Local\Temp\ipykernel_18080\3438781684.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime(clean_df["Date of Exam/Incident"])

0    2024-08-26
1    2024-08-04
2    2024-07-06
3    2024-06-30
4    2024-06-18
        ...
61   2016-05-01
62   2015-05-25
63   2015-05-03
64   2015-03-30
65   2014-06-23
Name: Date of Exam/Incident, Length: 66, dtype: datetime64[ns]

In [30]:
clean_df["Date of Exam/Incident"] = pd.to_datetime(
    clean_df["Date of Exam/Incident"],
    dayfirst=True
)

In [31]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date of Exam/Incident     66 non-null     datetime64[ns]
 1   Exam Name                 66 non-null     object
 2   Conducting Body           66 non-null     object
 3   Conducting Body Type      66 non-null     object
 4   Area(s) of Incident       66 non-null     object
 5   Leak Confirmation Status  66 non-null     object
 6   Action taken              66 non-null     object
 7   Note about action Taken   66 non-null     object
 8   Note about incident       66 non-null     object
 9   References                66 non-null     object
dtypes: datetime64[ns](1), object(9)
memory usage: 5.3+ KB

In [32]:
clean_df["Year"] = clean_df["Date of Exam/Incident"].dt.year

In [33]:
clean_df["Month"] = clean_df["Date of Exam/Incident"].dt.month_name()

In [34]:
clean_df["Month_No"] = clean_df["Date of Exam/Incident"].dt.month

In [35]:
clean_df["Quarter"] = clean_df["Date of Exam/Incident"].dt.quarter

In [36]:
clean_df.head()

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Year,Month,Month_No,Quarter
0,2024-08-26,B.Ed. 4th Sem Exam : Creating an Inclusive School,Tamil Nadu Teachers Education University,State,Tamilnadu,accused,Alternative Question Paper Used,Alternative Question Paper Used,Paper leaked on social media before exam,TNTEU registrar relieved after reports of B.Ed...,2024,August,8,3
1,2024-08-04,MBA 1st year Exam,Pondicherry University,Central,Pondicherry,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Pondicherry University First-year MBBS Exam Pa...,2024,August,8,3
2,2024-07-06,Foreign Medical Graduate Examination,National Board of Examinations in Medical Scie...,Central,Kerala,accused,Legal action taken and claim dismissed,"No Rexam and checking of evidence, claim dismi...",Paper leaked on social media,‘So far no evidence’: Kerala Police on FMGE ‘p...,2024,July,7,3
3,2024-06-30,Agriculture Development Officers,Punjab Public Service Comission,State,Punjab,accused,Unknown,No Rexam,Claim: Offical demanded bribe for leaking paper,"Now, ADO recruitment exam in Punjab under pape...",2024,June,6,2
4,2024-06-18,UGC NET 2024,National Testing Agency,Central,All India,accused,No Rexam,Exam cancellation decision overruled by Suprem...,accusation of paper leak,Supreme Court upholds decision to cancel UGC N...,2024,June,6,2

In [37]:
clean_df["Conducting Body"].unique()

array(['Tamil Nadu Teachers Education University',
       'Pondicherry University',
       'National Board of Examinations in Medical Sciences (NBEMS)',
       'Punjab Public Service Comission', 'National Testing Agency',
       'Tripura Tribal Areas Autonomous District Council',
       "Devi Ahilya Vishwavidyalaya's (DAVV)", 'VIT',
       'Bihar Public service Comission',
       'Jharkhand Public Service Commission',
       'Uttar Pradesh Police Recruitment and Promotion Board',
       'Assam Board of Secondary Education',
       'Uttar Pradesh Public Service Comission', 'Parul University',
       'West Bengal Board of Primary Education',
       'Tripura Board of Secondary Education (TBSE)',
       'Savitribai Phule\xa0Pune\xa0University',
       'Central Selection Board of Constables, Bihar', 'Private Center',
       'Barkatullah University', 'Odisha Staff Selection Commission',
       'AIIMS', 'Punjab School Education Board',
       'Telangana Board of intermediate Education',
       'Madhya Pradesh Board of Secondary Education',
       'Telangana State Public Service Commission',
       'Maharashtra State Board of Secondary and Higher Secondary Education',
       'Rajasthan Public Service Commission',
       'Rajasthan Staff Selection Board',
       'Himachal Pradesh Staff Selection Commission',
       'Arunachal Pradesh Public Service Commission',
       'The Uttar Pradesh Subordinate Services Selection Commission',
       'Uttar Pradesh State Board of High School and Intermediate Education',
       'Jammu and Kashmir Services Selection Board',
       'Bihar School Examination Board',
       'Maharashtra Housing and Area Development Authority',
       'Gujarat Subordinate Service Selection Board',
       'Uttarakhand Subordinate Staff Selection Commission',
       'Department of Basic Education, Uttar Pradesh',
       'BOARD OF SECONDARY EDUCATION, Rajasthan',
       'National Law School of India University',
       'Railway Recruitment Board', 'Kerala Public Service Commission',
       'Karnataka School Examination and Assessment Board',
       'Board of Secondary Education, Odisha',
       'Gujarat Police Recruitment Board',
       'Indria Gandhi National Open University', 'CBSE',
       'Staff Selection Comission',
       'Himachal Pradesh Board of School Education',
       'Haryana Public Service Commission',
       "King George's Medical University\xa0, Lucknow",
       "King George's Medical University\xa0, Ghaziabadd"], dtype=object)

In [38]:
clean_df["Conducting Body Type"].unique()

array(['State', 'Central', 'Private'], dtype=object)

In [39]:
clean_df["Area(s) of Incident"].unique()

array(['Tamilnadu', 'Pondicherry', 'Kerala', 'Punjab', 'All India',
       'Tripura', 'Madhya Pradesh', 'Bihar', 'Jharkhand', 'Uttar Pradesh',
       'Assam', 'Gujrat', 'West Bengal', 'Maharasthra', 'Odisha',
       'Telangana', 'Rajasthan', 'Himachal Pradesh', 'Arunachal Pradesh',
       'Jammu', 'Uttarakhand', 'Karnataka', 'Delhi', 'Haryana'],
      dtype=object)

In [40]:
clean_df["Leak Confirmation Status"].unique()

array(['accused', 'confirmed'], dtype=object)

In [41]:
clean_df["Action taken"].unique()

array(['Alternative Question Paper Used', 'Exam Cancelled',
       'Legal action taken and claim dismissed', 'Unknown', 'No Rexam',
       'Legal action taken', 'Chargesheet', 'Reports Denied',
       'Claim dissmissed', 'dismissed claim', 'No action taken',
       'Suspension', 'Exam Cancelled on many centers'], dtype=object)

In [42]:
clean_df["Conducting Body"].unique()

array(['Tamil Nadu Teachers Education University',
       'Pondicherry University',
       'National Board of Examinations in Medical Sciences (NBEMS)',
       'Punjab Public Service Comission', 'National Testing Agency',
       'Tripura Tribal Areas Autonomous District Council',
       "Devi Ahilya Vishwavidyalaya's (DAVV)", 'VIT',
       'Bihar Public service Comission',
       'Jharkhand Public Service Commission',
       'Uttar Pradesh Police Recruitment and Promotion Board',
       'Assam Board of Secondary Education',
       'Uttar Pradesh Public Service Comission', 'Parul University',
       'West Bengal Board of Primary Education',
       'Tripura Board of Secondary Education (TBSE)',
       'Savitribai Phule\xa0Pune\xa0University',
       'Central Selection Board of Constables, Bihar', 'Private Center',
       'Barkatullah University', 'Odisha Staff Selection Commission',
       'AIIMS', 'Punjab School Education Board',
       'Telangana Board of intermediate Education',
       'Madhya Pradesh Board of Secondary Education',
       'Telangana State Public Service Commission',
       'Maharashtra State Board of Secondary and Higher Secondary Education',
       'Rajasthan Public Service Commission',
       'Rajasthan Staff Selection Board',
       'Himachal Pradesh Staff Selection Commission',
       'Arunachal Pradesh Public Service Commission',
       'The Uttar Pradesh Subordinate Services Selection Commission',
       'Uttar Pradesh State Board of High School and Intermediate Education',
       'Jammu and Kashmir Services Selection Board',
       'Bihar School Examination Board',
       'Maharashtra Housing and Area Development Authority',
       'Gujarat Subordinate Service Selection Board',
       'Uttarakhand Subordinate Staff Selection Commission',
       'Department of Basic Education, Uttar Pradesh',
       'BOARD OF SECONDARY EDUCATION, Rajasthan',
       'National Law School of India University',
       'Railway Recruitment Board', 'Kerala Public Service Commission',
       'Karnataka School Examination and Assessment Board',
       'Board of Secondary Education, Odisha',
       'Gujarat Police Recruitment Board',
       'Indria Gandhi National Open University', 'CBSE',
       'Staff Selection Comission',
       'Himachal Pradesh Board of School Education',
       'Haryana Public Service Commission',
       "King George's Medical University\xa0, Lucknow",
       "King George's Medical University\xa0, Ghaziabadd"], dtype=object)

In [43]:
clean_df.to_csv("Paper_Leaks_Clean.csv", index=False)

In [44]:
# Total incidents by year
clean_df["Year"].value_counts().sort_index()

Year
2014     1
2015     3
2016     2
2017     3
2018     5
2019     3
2020     2
2021     8
2022    11
2023    15
2024    13
Name: count, dtype: int64

In [45]:
# Top Exam Names
clean_df["Exam Name"].value_counts()

Exam Name
High School Mathematics Exam                         3
Constable Exam                                       2
B.Ed. 4th Sem Exam : Creating an Inclusive School    1
JE Exam                                              1
Class 12th English                                   1
                                                    ..
Class 2nd Teacher Recruitment : GK Question Paper    1
Group 1 Prelims                                      1
Diploma in Elementary Education                      1
Forest Guard Recruitment                             1
UP CPMT 2014                                         1
Name: count, Length: 63, dtype: int64

In [46]:
# Top Conducting Bodies
clean_df["Conducting Body"].value_counts()

Conducting Body
Maharashtra State Board of Secondary and Higher Secondary Education    3
Uttar Pradesh Public Service Comission                                 3
CBSE                                                                   3
Bihar Public service Comission                                         2
Telangana State Public Service Commission                              2
Bihar School Examination Board                                         2
Railway Recruitment Board                                              2
Assam Board of Secondary Education                                     2
West Bengal Board of Primary Education                                 2
National Testing Agency                                                2
Indria Gandhi National Open University                                 1
Department of Basic Education, Uttar Pradesh                           1
Uttar Pradesh State Board of High School and Intermediate Education    1
Jammu and Kashmir Services Selection Board                             1
King George's Medical University , Lucknow                             1
Haryana Public Service Commission                                      1
Maharashtra Housing and Area Development Authority                     1
Gujarat Subordinate Service Selection Board                            1
Uttarakhand Subordinate Staff Selection Commission                     1
BOARD OF SECONDARY EDUCATION, Rajasthan                                1
Gujarat Police Recruitment Board                                       1
National Law School of India University                                1
Kerala Public Service Commission                                       1
Karnataka School Examination and Assessment Board                      1
Arunachal Pradesh Public Service Commission                            1
Board of Secondary Education, Odisha                                   1
Himachal Pradesh Board of School Education                             1
Staff Selection Comission                                              1
The Uttar Pradesh Subordinate Services Selection Commission            1
Tamil Nadu Teachers Education University                               1
Himachal Pradesh Staff Selection Commission                            1
Savitribai Phule Pune University                                       1
National Board of Examinations in Medical Sciences (NBEMS)             1
Punjab Public Service Comission                                        1
Tripura Tribal Areas Autonomous District Council                       1
Devi Ahilya Vishwavidyalaya's (DAVV)                                   1
VIT                                                                    1
Jharkhand Public Service Commission                                    1
Uttar Pradesh Police Recruitment and Promotion Board                   1
Parul University                                                       1
Tripura Board of Secondary Education (TBSE)                            1
Central Selection Board of Constables, Bihar                           1
Rajasthan Staff Selection Board                                        1
Private Center                                                         1
Barkatullah University                                                 1
Odisha Staff Selection Commission                                      1
AIIMS                                                                  1
Punjab School Education Board                                          1
Telangana Board of intermediate Education                              1
Madhya Pradesh Board of Secondary Education                            1
Pondicherry University                                                 1
Rajasthan Public Service Commission                                    1
King George's Medical University , Ghaziabadd                          1
Name: count, dtype: int64

In [47]:
# State-wise incidents
clean_df["Area(s) of Incident"].value_counts()

Area(s) of Incident
Uttar Pradesh        11
All India             7
Maharasthra           6
Bihar                 5
Gujrat                3
Kerala                3
Rajasthan             3
Madhya Pradesh        3
Telangana             3
Himachal Pradesh      2
Odisha                2
West Bengal           2
Assam                 2
Delhi                 2
Tripura               2
Punjab                2
Karnataka             1
Jammu                 1
Uttarakhand           1
Tamilnadu             1
Arunachal Pradesh     1
Pondicherry           1
Jharkhand             1
Haryana               1
Name: count, dtype: int64

In [48]:
# Leak confirmation status
clean_df["Leak Confirmation Status"].value_counts()

Leak Confirmation Status
confirmed    48
accused      18
Name: count, dtype: int64

In [49]:
import pandas as pd

In [51]:
import pandas as pd

df = pd.read_csv("Paper_Leaks_Clean.csv", encoding="cp1252")
df.head()

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Year,Month,Month_No,Quarter
0,2024-08-26,B.Ed. 4th Sem Exam : Creating an Inclusive School,Tamil Nadu Teachers Education University,State,Tamilnadu,accused,Alternative Question Paper Used,Alternative Question Paper Used,Paper leaked on social media before exam,TNTEU registrar relieved after reports of B.Ed...,2024,August,8,3
1,2024-08-04,MBA 1st year Exam,Pondicherry University,Central,Pondicherry,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Pondicherry University First-year MBBS Exam Pa...,2024,August,8,3
2,2024-07-06,Foreign Medical Graduate Examination,National Board of Examinations in Medical Scie...,Central,Kerala,accused,Legal action taken and claim dismissed,"No Rexam and checking of evidence, claim dismi...",Paper leaked on social media,â€˜So far no evidenceâ€™: Kerala Police on FMG...,2024,July,7,3
3,2024-06-30,Agriculture Development Officers,Punjab Public Service Comission,State,Punjab,accused,Unknown,No Rexam,Claim: Offical demanded bribe for leaking paper,"Now, ADO recruitment exam in Punjab under pape...",2024,June,6,2
4,2024-06-18,UGC NET 2024,National Testing Agency,Central,All India,accused,No Rexam,Exam cancellation decision overruled by Suprem...,accusation of paper leak,Supreme Court upholds decision to cancel UGC N...,2024,June,6,2

In [52]:
clean_df = df.copy()

In [ ]:
EDA (Exploratory Data Analysis)

In [53]:
# Total incidents by year
clean_df["Year"].value_counts().sort_index()

Year
2014     1
2015     3
2016     2
2017     3
2018     5
2019     3
2020     2
2021     8
2022    11
2023    15
2024    13
Name: count, dtype: int64

In [54]:
# Top Exam Names
clean_df["Exam Name"].value_counts()

Exam Name
High School Mathematics Exam                         3
Constable Exam                                       2
B.Ed. 4th Sem Exam : Creating an Inclusive School    1
JE Exam                                              1
Class 12th English                                   1
                                                    ..
Class 2nd Teacher Recruitment : GK Question Paper    1
Group 1 Prelims                                      1
Diploma in Elementary Education                      1
Forest Guard Recruitment                             1
UP CPMT 2014                                         1
Name: count, Length: 63, dtype: int64

In [55]:
# Top Conducting Bodies
clean_df["Conducting Body"].value_counts()

Conducting Body
Maharashtra State Board of Secondary and Higher Secondary Education    3
Uttar Pradesh Public Service Comission                                 3
CBSE                                                                   3
Bihar Public service Comission                                         2
Telangana State Public Service Commission                              2
Bihar School Examination Board                                         2
Railway Recruitment Board                                              2
Assam Board of Secondary Education                                     2
West Bengal Board of Primary Education                                 2
National Testing Agency                                                2
Indria Gandhi National Open University                                 1
Department of Basic Education, Uttar Pradesh                           1
Uttar Pradesh State Board of High School and Intermediate Education    1
Jammu and Kashmir Services Selection Board                             1
King George's Medical UniversityÂ , Lucknow                            1
Haryana Public Service Commission                                      1
Maharashtra Housing and Area Development Authority                     1
Gujarat Subordinate Service Selection Board                            1
Uttarakhand Subordinate Staff Selection Commission                     1
BOARD OF SECONDARY EDUCATION, Rajasthan                                1
Gujarat Police Recruitment Board                                       1
National Law School of India University                                1
Kerala Public Service Commission                                       1
Karnataka School Examination and Assessment Board                      1
Arunachal Pradesh Public Service Commission                            1
Board of Secondary Education, Odisha                                   1
Himachal Pradesh Board of School Education                             1
Staff Selection Comission                                              1
The Uttar Pradesh Subordinate Services Selection Commission            1
Tamil Nadu Teachers Education University                               1
Himachal Pradesh Staff Selection Commission                            1
Savitribai PhuleÂ PuneÂ University                                     1
National Board of Examinations in Medical Sciences (NBEMS)             1
Punjab Public Service Comission                                        1
Tripura Tribal Areas Autonomous District Council                       1
Devi Ahilya Vishwavidyalaya's (DAVV)                                   1
VIT                                                                    1
Jharkhand Public Service Commission                                    1
Uttar Pradesh Police Recruitment and Promotion Board                   1
Parul University                                                       1
Tripura Board of Secondary Education (TBSE)                            1
Central Selection Board of Constables, Bihar                           1
Rajasthan Staff Selection Board                                        1
Private Center                                                         1
Barkatullah University                                                 1
Odisha Staff Selection Commission                                      1
AIIMS                                                                  1
Punjab School Education Board                                          1
Telangana Board of intermediate Education                              1
Madhya Pradesh Board of Secondary Education                            1
Pondicherry University                                                 1
Rajasthan Public Service Commission                                    1
King George's Medical UniversityÂ , Ghaziabadd                         1
Name: count, dtype: int64

In [56]:
# State-wise incidents
clean_df["Area(s) of Incident"].value_counts()

Area(s) of Incident
Uttar Pradesh        11
All India             7
Maharasthra           6
Bihar                 5
Gujrat                3
Kerala                3
Rajasthan             3
Madhya Pradesh        3
Telangana             3
Himachal Pradesh      2
Odisha                2
West Bengal           2
Assam                 2
Delhi                 2
Tripura               2
Punjab                2
Karnataka             1
Jammu                 1
Uttarakhand           1
Tamilnadu             1
Arunachal Pradesh     1
Pondicherry           1
Jharkhand             1
Haryana               1
Name: count, dtype: int64

In [57]:
# Leak confirmation status
clean_df["Leak Confirmation Status"].value_counts()

Leak Confirmation Status
confirmed    48
accused      18
Name: count, dtype: int64

In [58]:
clean_df["Exam Name"].value_counts().head(10)

Exam Name
High School Mathematics Exam                         3
Constable Exam                                       2
B.Ed. 4th Sem Exam : Creating an Inclusive School    1
JE Exam                                              1
Class 12th English                                   1
sub-inspector recruitment examination                1
MHADA Exam                                           1
Head Clerk                                           1
UKSSSC Exam                                          1
Uttar Pradesh Teacher Eligbility Test                1
Name: count, dtype: int64